// <auto-generated />
using System;
using CPA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPA.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240604165543_m")]
    partial class m
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CPA.Core.Entities.cpa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeniorityYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CPAList");
                });

            modelBuilder.Entity("CPA.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomersList");
                });

            modelBuilder.Entity("CPA.Core.Entities.Meet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CPAId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("MeetingDuration")
                        .HasColumnType("float");

                    b.Property<int>("MeetingHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CPAId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MeetsList");
                });

            modelBuilder.Entity("CPA.Core.Entities.Meet", b =>
                {
                    b.HasOne("CPA.Core.Entities.cpa", "CPA")
                        .WithMany("Meets")
                        .HasForeignKey("CPAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPA.Core.Entities.Customer", "Customer")
                        .WithMany("Meets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CPA");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CPA.Core.Entities.cpa", b =>
                {
                    b.Navigation("Meets");
                });

            modelBuilder.Entity("CPA.Core.Entities.Customer", b =>
                {
                    b.Navigation("Meets");
                });
#pragma warning restore 612, 618
        }
    }
}
